apiVersion: batch/v1
kind: CronJob
metadata:
  name: classcronjob-pi
spec:
  schedule: "*/2 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron
            image: alpine:latest
            command:
            args: 
            - "/bin/bash"
            - "-c"
            - 'echo "Ivan Uribe"'
          restartPolicy: Never
      backoffLimit: 4

