apiVersion: batch/v1
kind: Deployment
metadata:
  name: deployment
spec:
replicas: 1
containers:
  - name: web
  image: nginx:latest
    volumeMounts:
    - mountPath: /temp/ckad
      name: empty-test
  volumes:
  - name: empty-test
  emptyDir: {}